// Angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'Angular';
}

<p>
  Ceza mı bu<br>
  Çektiğim çile mi<br>
  Yıllardır tuttuğum nöbet bitmeyecek mi?<br>
  Bir küçük kar tanesi gibiyim<br>
  Avucunda eriyen dön bebeğim<br>
  <br>
  Gözyaşlarını görürsem<br>
  Erir kanatlarım<br>
  Uçamam rüyalarında yanına<br>
  Sonsuzluk senle başladı<br>
  O küçük dünyamda<br>
  Unutma gittiğinde yarım kaldım<br>
  <br>
  Çöllerdeyim yanıyorum<br>
  Kutuptayım üşüyorum<br>
  Ceza benim çekiyorum ne olur dön<br>
  Uzanıyorum tutamıyorum<br>
  Özlüyorum ağlıyorum<br>
  Yasak mısın anlamıyorum ne olur dön<br>
  <br>
  Sevmesen de beni özledim sesini<br>
  Git desem de yine gitmesen<br>
  Yıllardır çektiğim bu hasret mi çile mi?<br>
  Haram mısın bana bi' bilsem<br>
  <br>
  Sevmesen de beni özledim sesini<br>
  Git desem de yine gitmesen<br>
  Yıllardır çektiğim bu hasret mi çile mi?<br>
  Haram mısın bana bi' bilsem<br>
  <br>
  Bebeğim benim, hayalet sevgilim<br>
  Bebeğim benim, hayalet sevgilim<br>
  <br>
  Hayalet sevgilim<br>
  <br>
  Çöllerdeyim yanıyorum<br>
  Kutuptayım üşüyorum<br>
  Ceza benim çekiyorum ne olur dön<br>
  Uzanıyorum tutamıyorum<br>
  Özlüyorum ağlıyorum<br>
  Yasak mısın anlamıyorum ne olur dön<br>
  <br>
  Sevmesen de beni özledim sesini<br>
  Git desem de yine gitmesen<br>
  Yıllardır çektiğim bu hasret mi çile mi?<br>
  Haram mısın bana bi' bilsem<br>
  <br>
  Sevmesen de beni özledim sesini<br>
  Git desem de yine gitmesen<br>
  Yıllardır çektiğim bu hasret mi çile mi?<br>
  Haram mısın bana bi' bilsem<br>
  <br>
  Bebeğim benim hayalet sevgilim<br>
  Bebeğim benim hayalet sevgilim<br>
  <br>
  Hayalet sevgilim<br>
  Hayalet sevgilim<br>
</p>

// svelte/src/App.svelte
<script>
	export let singer, songTitle;

const data = [
  "Ceza mı bu",
  "Çektiğim çile mi",
  "Yıllardır tuttuğum nöbet bitmeyecek mi?",
  "Bir küçük kar tanesi gibiyim",
  "Avucunda eriyen dön bebeğim",
  "",
  "Gözyaşlarını görürsem",
  "Erir kanatlarım",
  "Uçamam rüyalarında yanına",
  "Sonsuzluk senle başladı",
  "O küçük dünyamda",
  "Unutma gittiğinde yarım kaldım",
  "",
  "Çöllerdeyim yanıyorum",
  "Kutuptayım üşüyorum",
  "Ceza benim çekiyorum ne olur dön",
  "Uzanıyorum tutamıyorum",
  "Özlüyorum ağlıyorum",
  "Yasak mısın anlamıyorum ne olur dön",
  "",
  "Sevmesen de beni özledim sesini",
  "Git desem de yine gitmesen",
  "Yıllardır çektiğim bu hasret mi çile mi?",
  "Haram mısın bana bi' bilsem",
  "",
  "Sevmesen de beni özledim sesini",
  "Git desem de yine gitmesen",
  "Yıllardır çektiğim bu hasret mi çile mi?",
  "Haram mısın bana bi' bilsem",
  "",
  "Bebeğim benim, hayalet sevgilim",
  "Bebeğim benim, hayalet sevgilim",
  "",
  "Hayalet sevgilim",
  "",
  "Çöllerdeyim yanıyorum",
  "Kutuptayım üşüyorum",
  "Ceza benim çekiyorum ne olur dön",
  "Uzanıyorum tutamıyorum",
  "Özlüyorum ağlıyorum",
  "Yasak mısın anlamıyorum ne olur dön",
  "",
  "Sevmesen de beni özledim sesini",
  "Git desem de yine gitmesen",
  "Yıllardır çektiğim bu hasret mi çile mi?",
  "Haram mısın bana bi' bilsem",
  "",
  "Sevmesen de beni özledim sesini",
  "Git desem de yine gitmesen",
  "Yıllardır çektiğim bu hasret mi çile mi?",
  "Haram mısın bana bi' bilsem",
  "",
  "Bebeğim benim hayalet sevgilim",
  "Bebeğim benim hayalet sevgilim",
  "",
  "Hayalet sevgilim",
  "Hayalet sevgilim"
]
</script>

<main>
	<h1>{singer}'dan {songTitle}</h1>
	<ul>
		{#each data as lyric}
			<li>{lyric}</li>
		{/each}
	</ul>
</main>	

<style>
	main {
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	h1 {
		color: #ff3e00;
		text-transform: uppercase;
		font-size: 4em;
		font-weight: 100;
	}

	li {
		list-style-type: none;
	}

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}
</style>
